#!/bin/bash
set -e

# All variables must be set via environment (compose.yml)
: "${CRAWLER_DB_NAME:?CRAWLER_DB_NAME is not set}"
: "${CRAWLER_DB_USER:?CRAWLER_DB_USER is not set}"
: "${CRAWLER_DB_PASSWORD:?CRAWLER_DB_PASSWORD is not set}"
: "${ROOKHUB_DB_NAME:?ROOKHUB_DB_NAME is not set}"
: "${ROOKHUB_DB_USER:?ROOKHUB_DB_USER is not set}"
: "${ROOKHUB_DB_PASSWORD:?ROOKHUB_DB_PASSWORD is not set}"

docker_process_sql <<-EOSQL
CREATE DATABASE IF NOT EXISTS \`${CRAWLER_DB_NAME}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '${CRAWLER_DB_USER}'@'%' IDENTIFIED BY '${CRAWLER_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON \`${CRAWLER_DB_NAME}\`.* TO '${CRAWLER_DB_USER}'@'%';

CREATE DATABASE IF NOT EXISTS \`${ROOKHUB_DB_NAME}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '${ROOKHUB_DB_USER}'@'%' IDENTIFIED BY '${ROOKHUB_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON \`${ROOKHUB_DB_NAME}\`.* TO '${ROOKHUB_DB_USER}'@'%';

FLUSH PRIVILEGES;
EOSQL
