#!/bin/bash
# Uses env vars from compose.yml, falls back to defaults

CRAWLER_DB="${CRAWLER_DB_NAME:-chessresults}"
CRAWLER_USER="${CRAWLER_DB_USER:-chessresults}"
CRAWLER_PASS="${CRAWLER_DB_PASSWORD:-chessresults}"
ROOKHUB_DB="${ROOKHUB_DB_NAME:-rookhub}"
ROOKHUB_USER="${ROOKHUB_DB_USER:-rookhub}"
ROOKHUB_PASS="${ROOKHUB_DB_PASSWORD:-rookhub_secret}"

mariadb -u root -p"${MYSQL_ROOT_PASSWORD}" <<-EOSQL
CREATE DATABASE IF NOT EXISTS \`${CRAWLER_DB}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '${CRAWLER_USER}'@'%' IDENTIFIED BY '${CRAWLER_PASS}';
GRANT ALL PRIVILEGES ON \`${CRAWLER_DB}\`.* TO '${CRAWLER_USER}'@'%';

CREATE DATABASE IF NOT EXISTS \`${ROOKHUB_DB}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '${ROOKHUB_USER}'@'%' IDENTIFIED BY '${ROOKHUB_PASS}';
GRANT ALL PRIVILEGES ON \`${ROOKHUB_DB}\`.* TO '${ROOKHUB_USER}'@'%';

FLUSH PRIVILEGES;
EOSQL
