-- „1001 Deadly Checkmates": Nach-(Re-)Import-Fixup — NACH JEDEM NEUIMPORT EINSPIELEN.
-- Macht zwei Dinge:
--   1) Kapitelnamen entschärfen: „Chapter N: <Motiv>" → „Chapter N" (das Motiv wäre sonst ein
--      Spoiler). Re-Import überschreibt das Chapter-Feld → daher nach jedem Import erneut nötig.
--   2) Vorberechnete Tipps wiederherstellen (Sicherungsnetz, falls Buch gelöscht + neu importiert
--      oder unter anderem Nutzer/bid importiert wurde). Beim normalen Re-Import bleibt HintsJson
--      ohnehin erhalten — dann sind die Tipp-UPDATEs nur idempotente No-ops.
--
-- Matcht per stabilem Suffix (Kapitel.Nummer, z. B. :003.004) bzw. Buchdatei → trifft sowohl den
-- Chessable-Kurs (chessable-u5-49690.pgn) als auch die firstkey-Kopie (…_firstkey.pgn), Dev wie Prod.
--
-- Anwenden (Beispiel Dev):
--   docker exec -i rookhub-mariadb-dev mariadb -u<user> -p'<pw>' rookhub < scripts/hints/1001_deadly_checkmates.sql
-- (Prod analog gegen den rookhub-mariadb-Container.)
--
-- Stand Tipps: 8 Puzzles (Kapitel-Anfang 003.004–003.011). Wird mit jeder weiteren Charge ergänzt.

-- 1) Kapitelnamen entschärfen (idempotent: bereits gekürzte „Chapter N" haben keinen Doppelpunkt).
UPDATE BookPuzzles SET Chapter = SUBSTRING_INDEX(Chapter, ':', 1)
  WHERE BookFileName IN ('chessable-u5-49690.pgn','1001 Deadly Checkmates_firstkey.pgn')
    AND Chapter LIKE 'Chapter %:%';

-- 2) Tipps (wiederherstellen / sichern):

UPDATE BookPuzzles SET HintsJson='{"de":["Der König klebt am Rand und sein einziger Verteidiger ist gefesselt.","Ein Turm gibt das Matt, unterstützt von deinem Läufer; der gegnerische Läufer kann nicht eingreifen.","Turm nach c8 – matt."],"en":["The king is stuck on the back rank and its only defender is pinned.","A rook delivers mate, supported by your bishop; the defending bishop cannot interpose.","Rook to c8 — mate."],"hr":["Kralj je zaglavljen na zadnjem redu, a jedini branitelj mu je vezan.","Top daje mat uz potporu tvojeg lovca; protivnički lovac ne može se umiješati.","Top na c8 — mat."]}', HintsVersion=1 WHERE LineId LIKE '%:003.004' AND BookFileName IN ('chessable-u5-49690.pgn','1001 Deadly Checkmates_firstkey.pgn');
UPDATE BookPuzzles SET HintsJson='{"de":["Der gegnerische König steht ungeschützt im Zentrum, eingeengt von eigenen Figuren.","Ein Springerschach nimmt ihm jedes Fluchtfeld; nichts kann schlagen oder dazwischenziehen.","Springer nach f4 – matt."],"en":["The enemy king is caught in the open centre, boxed in by its own men.","A knight check seals every escape; nothing can capture or block it.","Knight to f4 — mate."],"hr":["Protivnički kralj zaglavljen je u središtu, stiješnjen vlastitim figurama.","Šah skakačem oduzima mu svako polje za bijeg; ništa ne može uzeti ni zakloniti.","Skakač na f4 — mat."]}', HintsVersion=1 WHERE LineId LIKE '%:003.005' AND BookFileName IN ('chessable-u5-49690.pgn','1001 Deadly Checkmates_firstkey.pgn');
UPDATE BookPuzzles SET HintsJson='{"de":["Der gegnerische König ist zu weit vorgerückt und deine Figuren umzingeln ihn.","Ein Springerschach beendet die Partie; der Turm sperrt bereits den Fluchtweg.","Springer nach e4 – matt."],"en":["The enemy king has advanced too far and your pieces surround it.","A knight check finishes it; the rook already cuts off the escape.","Knight to e4 — mate."],"hr":["Protivnički kralj otišao je predaleko naprijed, a tvoje figure ga okružuju.","Šah skakačem završava partiju; top već presijeca put za bijeg.","Skakač na e4 — mat."]}', HintsVersion=1 WHERE LineId LIKE '%:003.006' AND BookFileName IN ('chessable-u5-49690.pgn','1001 Deadly Checkmates_firstkey.pgn');
UPDATE BookPuzzles SET HintsJson='{"de":["Der weiße König ist ringsum von Bauern eingemauert; ein Schach genügt.","Schwenke den Turm auf die offene Linie; alle Fluchtfelder sind bereits gedeckt.","Turm nach f3 – matt."],"en":["The white king is walled in by pawns on every side; one check is enough.","Swing your rook onto the open file; every flight square is already covered.","Rook to f3 — mate."],"hr":["Bijeli kralj je sa svih strana zazidan pješacima; jedan šah je dovoljan.","Prebaci top na otvorenu liniju; sva polja za bijeg već su pokrivena.","Top na f3 — mat."]}', HintsVersion=1 WHERE LineId LIKE '%:003.007' AND BookFileName IN ('chessable-u5-49690.pgn','1001 Deadly Checkmates_firstkey.pgn');
UPDATE BookPuzzles SET HintsJson='{"de":["Ein aufgedecktes Doppelschach lässt dem König nur die Flucht, die ihm fehlt.","Zieh den Springer so, dass er Schach bietet und zugleich die Dame Schach gibt.","Springer nach f6 – Doppelschach und matt."],"en":["A discovered double check leaves the king nothing but to run, and it cannot.","Move the knight so it gives check while your queen unveils a second check.","Knight to f6 — double check and mate."],"hr":["Otkriveni dvostruki šah ne ostavlja kralju ništa osim bijega, kojeg nema.","Pomakni skakača tako da daje šah dok dama otkriva drugi šah.","Skakač na f6 — dvostruki šah i mat."]}', HintsVersion=1 WHERE LineId LIKE '%:003.008' AND BookFileName IN ('chessable-u5-49690.pgn','1001 Deadly Checkmates_firstkey.pgn');
UPDATE BookPuzzles SET HintsJson='{"de":["Der in die Ecke gedrängte König hat kaum Felder; dein Läufer deckt still den Rest.","Bring die Dame auf die Grundreihe und beherrsche Reihe und Fluchtdiagonale.","Dame nach b1 – matt."],"en":["The cornered king has almost no squares, and your bishop quietly guards the rest.","Bring your queen to the back rank to seize the row and the escape diagonal.","Queen to b1 — mate."],"hr":["Kralj sabijen u kut gotovo da nema polja, a tvoj lovac tiho čuva ostatak.","Dovedi damu na zadnji red i preuzmi red i dijagonalu za bijeg.","Dama na b1 — mat."]}', HintsVersion=1 WHERE LineId LIKE '%:003.009' AND BookFileName IN ('chessable-u5-49690.pgn','1001 Deadly Checkmates_firstkey.pgn');
UPDATE BookPuzzles SET HintsJson='{"de":["Der König kommt aus seiner eigenen Grundreihe nicht heraus; der schlagende Bauer ist gefesselt.","Ein Springer dringt mit Schach ein; der Turm auf der offenen Linie lähmt den einzigen Schlag.","Springer nach b3 – matt."],"en":["The king cannot escape its own back rank, and the pawn that could capture is pinned.","A knight leaps in with check; the rook on the open file freezes the only capture.","Knight to b3 — mate."],"hr":["Kralj ne može pobjeći iz vlastitog zadnjeg reda, a pješak koji bi uzeo je vezan.","Skakač uskače sa šahom; top na otvorenoj liniji sprječava jedino uzimanje.","Skakač na b3 — mat."]}', HintsVersion=1 WHERE LineId LIKE '%:003.010' AND BookFileName IN ('chessable-u5-49690.pgn','1001 Deadly Checkmates_firstkey.pgn');
UPDATE BookPuzzles SET HintsJson='{"de":["Der schwarze König ist an den Rand getrieben; beide Läufer und Bauern decken die Ausgänge.","Ein ruhiges Läuferschach auf der Diagonale nimmt das letzte Feld.","Läufer nach f4 – matt."],"en":["The black king is driven to the edge; both your bishops and pawns cover the exits.","A quiet bishop check along the diagonal takes the last square.","Bishop to f4 — mate."],"hr":["Crni kralj je sabijen na rub; oba tvoja lovca i pješaci pokrivaju izlaze.","Tihi šah lovcem po dijagonali oduzima posljednje polje.","Lovac na f4 — mat."]}', HintsVersion=1 WHERE LineId LIKE '%:003.011' AND BookFileName IN ('chessable-u5-49690.pgn','1001 Deadly Checkmates_firstkey.pgn');
